
export interface MarketPriceEntry {
  commodity: string;
  unit: string;
  basePrice: number;
  category: "Vegetable" | "Fruit" | "Grain" | "Pulse" | "Flour";
}

export const MARKET_DATASET: MarketPriceEntry[] = [
  // Vegetables
  { commodity: "Beans", unit: "1 Kg", basePrice: 80, category: "Vegetable" },
  { commodity: "Beans Broad", unit: "1 Kg", basePrice: 60, category: "Vegetable" },
  { commodity: "Beetroot", unit: "1 Kg", basePrice: 40, category: "Vegetable" },
  { commodity: "Bitter Gourd", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Bottle Gourd", unit: "1 Kg", basePrice: 20, category: "Vegetable" },
  { commodity: "Brinjal", unit: "1 Kg", basePrice: 30, category: "Vegetable" },
  { commodity: "Cabbage", unit: "1 Kg", basePrice: 25, category: "Vegetable" },
  { commodity: "Capsicum", unit: "1 Kg", basePrice: 60, category: "Vegetable" },
  { commodity: "Carrot", unit: "1 Kg", basePrice: 70, category: "Vegetable" },
  { commodity: "Cauliflower", unit: "1 Piece", basePrice: 30, category: "Vegetable" },
  { commodity: "Chayote", unit: "1 Kg", basePrice: 30, category: "Vegetable" },
  { commodity: "Colocasia", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Coriander Leaves", unit: "1 Bunch", basePrice: 15, category: "Vegetable" },
  { commodity: "Cucumber", unit: "1 Kg", basePrice: 30, category: "Vegetable" },
  { commodity: "Drumstick", unit: "1 Kg", basePrice: 80, category: "Vegetable" },
  { commodity: "Ginger", unit: "1 Kg", basePrice: 180, category: "Vegetable" },
  { commodity: "Green Chili", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Kohlrabi", unit: "1 Kg", basePrice: 25, category: "Vegetable" },
  { commodity: "Ladies Finger", unit: "1 Kg", basePrice: 40, category: "Vegetable" },
  { commodity: "Mint", unit: "1 Bunch", basePrice: 10, category: "Vegetable" },
  { commodity: "Onion", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Onion Small", unit: "1 Kg", basePrice: 80, category: "Vegetable" },
  { commodity: "Plantain Flower", unit: "1 Piece", basePrice: 30, category: "Vegetable" },
  { commodity: "Plantain Raw Banana", unit: "1 Piece", basePrice: 10, category: "Vegetable" },
  { commodity: "Plantain Stem", unit: "1 Piece", basePrice: 10, category: "Vegetable" },
  { commodity: "Potato", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Pumpkin", unit: "1 Kg", basePrice: 20, category: "Vegetable" },
  { commodity: "Radish", unit: "1 Kg", basePrice: 30, category: "Vegetable" },
  { commodity: "Ridge Gourd", unit: "1 Kg", basePrice: 20, category: "Vegetable" },
  { commodity: "Scarlet Gourd", unit: "1 Kg", basePrice: 25, category: "Vegetable" },
  { commodity: "Snake Gourd", unit: "1 Kg", basePrice: 25, category: "Vegetable" },
  { commodity: "Sweet Potato", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  { commodity: "Tapioca", unit: "1 Kg", basePrice: 30, category: "Vegetable" },
  { commodity: "Tomato Hybrid", unit: "1 Kg", basePrice: 35, category: "Vegetable" },
  { commodity: "Tomato Local", unit: "1 Kg", basePrice: 35, category: "Vegetable" },
  { commodity: "Yam", unit: "1 Kg", basePrice: 50, category: "Vegetable" },
  
  // Fruits
  { commodity: "Apple", unit: "1 Kg", basePrice: 200, category: "Fruit" },
  { commodity: "Avocado", unit: "1 Kg", basePrice: 200, category: "Fruit" },
  { commodity: "Banana Green", unit: "1 Kg", basePrice: 40, category: "Fruit" },
  { commodity: "Banana Red", unit: "1 Kg", basePrice: 60, category: "Fruit" },
  { commodity: "Banana Yellow", unit: "1 Kg", basePrice: 40, category: "Fruit" },
  { commodity: "Cherry", unit: "1 Kg", basePrice: 600, category: "Fruit" },
  { commodity: "Coconut", unit: "1 Piece", basePrice: 30, category: "Fruit" },
  { commodity: "Custard Apple", unit: "1 Kg", basePrice: 50, category: "Fruit" },
  { commodity: "Date", unit: "1 Kg", basePrice: 300, category: "Fruit" },
  { commodity: "Fig", unit: "1 Kg", basePrice: 150, category: "Fruit" },
  { commodity: "Gooseberry", unit: "1 Kg", basePrice: 100, category: "Fruit" },
  { commodity: "Grape Black", unit: "1 Kg", basePrice: 60, category: "Fruit" },
  { commodity: "Grape Black Seedless", unit: "1 Kg", basePrice: 80, category: "Fruit" },
  { commodity: "Grape Green", unit: "1 Kg", basePrice: 70, category: "Fruit" },
  { commodity: "Grape Green Seedless", unit: "1 Kg", basePrice: 90, category: "Fruit" },
  { commodity: "Jackfruit", unit: "1 Piece", basePrice: 500, category: "Fruit" },
  { commodity: "Lemon", unit: "1 Kg", basePrice: 100, category: "Fruit" },
  { commodity: "Mango", unit: "1 Kg", basePrice: 80, category: "Fruit" },
  { commodity: "Mosambi", unit: "1 Kg", basePrice: 60, category: "Fruit" },
  { commodity: "Orange", unit: "1 Kg", basePrice: 70, category: "Fruit" },
  { commodity: "Papaya", unit: "1 Kg", basePrice: 50, category: "Fruit" },
  { commodity: "Peach", unit: "1 Kg", basePrice: 220, category: "Fruit" },
  { commodity: "Pear", unit: "1 Kg", basePrice: 180, category: "Fruit" },
  { commodity: "Pineapple", unit: "1 Kg", basePrice: 60, category: "Fruit" },
  { commodity: "Plum", unit: "1 Kg", basePrice: 280, category: "Fruit" },
  { commodity: "Pomegranate", unit: "1 Kg", basePrice: 150, category: "Fruit" },
  { commodity: "Sapota", unit: "1 Kg", basePrice: 70, category: "Fruit" },
  { commodity: "Strawberry", unit: "1 Kg", basePrice: 420, category: "Fruit" },
  { commodity: "Watermelon", unit: "1 Kg", basePrice: 25, category: "Fruit" },

  // Grains / Rice
  { commodity: "Basmati Rice", unit: "1 Kg", basePrice: 120, category: "Grain" },
  { commodity: "Black Rice", unit: "1 Kg", basePrice: 120, category: "Grain" },
  { commodity: "Idli Rice", unit: "1 Kg", basePrice: 40, category: "Grain" },
  { commodity: "Kolam Rice", unit: "1 Kg", basePrice: 60, category: "Grain" },
  { commodity: "Ponni Rice Boiled", unit: "1 Kg", basePrice: 55, category: "Grain" },
  { commodity: "Ponni Rice Raw", unit: "1 Kg", basePrice: 60, category: "Grain" },
  { commodity: "Red Rice", unit: "1 Kg", basePrice: 80, category: "Grain" },
  { commodity: "Sona Masoori Rice Raw", unit: "1 Kg", basePrice: 60, category: "Grain" },
  { commodity: "Sona Masoori Rice Steamed", unit: "1 Kg", basePrice: 50, category: "Grain" },
  { commodity: "Paddy", unit: "1 Kg", basePrice: 22, category: "Grain" },
  { commodity: "Buckwheat", unit: "1 Kg", basePrice: 60, category: "Grain" },
  { commodity: "Mustard", unit: "1 Kg", basePrice: 65, category: "Grain" },
  { commodity: "Safflower", unit: "1 Kg", basePrice: 55, category: "Grain" },

  // Dals / Pulses
  { commodity: "Black Masoor Dal Split", unit: "1 Kg", basePrice: 100, category: "Pulse" },
  { commodity: "Black Masoor Dal Whole", unit: "1 Kg", basePrice: 100, category: "Pulse" },
  { commodity: "Black Urad Dal Split", unit: "1 Kg", basePrice: 130, category: "Pulse" },
  { commodity: "Black Urad Dal Whole", unit: "1 Kg", basePrice: 120, category: "Pulse" },
  { commodity: "Chana Dal", unit: "1 Kg", basePrice: 80, category: "Pulse" },
  { commodity: "Fried Bengal Gram Split", unit: "1 Kg", basePrice: 120, category: "Pulse" },
  { commodity: "Fried Bengal Gram Whole", unit: "1 Kg", basePrice: 120, category: "Pulse" },
  { commodity: "Green Moong Dal Split", unit: "1 Kg", basePrice: 110, category: "Pulse" },
  { commodity: "Green Moong Dal Whole", unit: "1 Kg", basePrice: 120, category: "Pulse" },
  { commodity: "Horse Gram", unit: "1 Kg", basePrice: 80, category: "Pulse" },
  { commodity: "Red Masoor Dal Split", unit: "1 Kg", basePrice: 140, category: "Pulse" },
  { commodity: "Red Masoor Dal Whole", unit: "1 Kg", basePrice: 140, category: "Pulse" },
  { commodity: "Toor Dal", unit: "1 Kg", basePrice: 110, category: "Pulse" },
  { commodity: "White Urad Dal Split", unit: "1 Kg", basePrice: 130, category: "Pulse" },
  { commodity: "White Urad Dal Whole", unit: "1 Kg", basePrice: 120, category: "Pulse" },
  { commodity: "Yellow Moong Dal Split", unit: "1 Kg", basePrice: 150, category: "Pulse" },
  { commodity: "Yellow Moong Dal Whole", unit: "1 Kg", basePrice: 130, category: "Pulse" },

  // Flours
  { commodity: "Bajra Flour", unit: "1 Kg", basePrice: 80, category: "Flour" },
  { commodity: "Besan", unit: "1 Kg", basePrice: 80, category: "Flour" },
  { commodity: "Jowar Flour", unit: "1 Kg", basePrice: 50, category: "Flour" },
  { commodity: "Maida", unit: "1 Kg", basePrice: 40, category: "Flour" },
  { commodity: "Ragi Flour", unit: "1 Kg", basePrice: 55, category: "Flour" },
  { commodity: "Rava", unit: "1 Kg", basePrice: 50, category: "Flour" },
  { commodity: "Rice Flour", unit: "1 Kg", basePrice: 50, category: "Flour" },
  { commodity: "Soyabean Aata", unit: "1 Kg", basePrice: 80, category: "Flour" },
  { commodity: "Wheat Aata", unit: "1 Kg", basePrice: 45, category: "Flour" },
];
